#!/usr/bin/env python3
"""
Scan img/travel/ for photos with GPS EXIF data and generate
assets/js/places.js for the 3D globe on the travel page.

Usage: python3 build-travel.py
Run this after adding/removing photos in img/travel/.
"""

import os, json, time, urllib.request, urllib.parse
from PIL import Image
from PIL.ExifTags import TAGS, GPSTAGS

TRAVEL_DIR = 'img/travel'
OUTPUT = 'assets/js/places.js'

def reverse_geocode(lat, lng):
    """Convert lat/lng to 'City, State' using free Nominatim API via curl."""
    try:
        import subprocess
        url = f'https://nominatim.openstreetmap.org/reverse?lat={lat}&lon={lng}&format=json&zoom=10'
        result = subprocess.run(['curl', '-s', url, '-H', 'User-Agent: travel-build/1.0'],
                                capture_output=True, text=True, timeout=15)
        data = json.loads(result.stdout)
        addr = data.get('address', {})
        city = addr.get('city') or addr.get('town') or addr.get('village') or addr.get('county') or ''
        state = addr.get('state') or addr.get('country') or ''
        if city and state:
            return f'{city}, {state}'
        return city or state or f'{lat:.2f}, {lng:.2f}'
    except Exception as e:
        print(f"    Geocode failed: {e}")
        return f'{lat:.2f}, {lng:.2f}'

def get_exif_gps(path):
    """Extract GPS lat/lng and date from image EXIF data."""
    try:
        img = Image.open(path)
        exif = img._getexif()
        if not exif:
            return None

        gps_info = {}
        date = ''
        for tag_id, value in exif.items():
            tag = TAGS.get(tag_id, tag_id)
            if tag == 'GPSInfo':
                for gps_tag_id, gps_value in value.items():
                    gps_tag = GPSTAGS.get(gps_tag_id, gps_tag_id)
                    gps_info[gps_tag] = gps_value
            elif tag == 'DateTimeOriginal' or (tag == 'DateTime' and not date):
                date = str(value)

        if not gps_info:
            return None

        def to_decimal(dms, ref):
            d, m, s = [float(x) for x in dms]
            decimal = d + m/60 + s/3600
            if ref in ('S', 'W'):
                decimal = -decimal
            return round(decimal, 6)

        lat = to_decimal(gps_info.get('GPSLatitude', (0,0,0)),
                         gps_info.get('GPSLatitudeRef', 'N'))
        lng = to_decimal(gps_info.get('GPSLongitude', (0,0,0)),
                         gps_info.get('GPSLongitudeRef', 'E'))

        return {'lat': lat, 'lng': lng, 'date': date[:10].replace(':', '-') if date else ''}
    except Exception as e:
        print(f"  Warning: {path} - {e}")
        return None

def main():
    if not os.path.isdir(TRAVEL_DIR):
        print(f"Directory {TRAVEL_DIR} not found")
        return

    files = sorted([f for f in os.listdir(TRAVEL_DIR)
                    if f.lower().endswith(('.jpg', '.jpeg', '.png', '.webp', '.heic'))])

    places = []
    seen_coords = {}
    for f in files:
        path = os.path.join(TRAVEL_DIR, f)
        gps = get_exif_gps(path)
        if gps:
            # Reverse geocode (cache by rounded coords to avoid redundant API calls)
            coord_key = f"{gps['lat']:.2f},{gps['lng']:.2f}"
            if coord_key not in seen_coords:
                location = reverse_geocode(gps['lat'], gps['lng'])
                seen_coords[coord_key] = location
                time.sleep(1)  # respect Nominatim rate limit
            else:
                location = seen_coords[coord_key]

            places.append({
                'file': f,
                'lat': gps['lat'],
                'lng': gps['lng'],
                'date': gps['date'],
                'location': location,
            })
            print(f"  ✓ {f} → {location} ({gps['lat']}, {gps['lng']}) {gps['date']}")
        else:
            print(f"  ✗ {f} — no GPS data, skipping")

    # Generate JS
    js_lines = [
        '/*',
        ' * places.js — Auto-generated by build-travel.py',
        ' * DO NOT EDIT MANUALLY. Run: python3 build-travel.py',
        ' */',
        f'const PLACES = {json.dumps(places, indent=2)};',
    ]

    with open(OUTPUT, 'w') as f:
        f.write('\n'.join(js_lines) + '\n')

    print(f"\nGenerated {OUTPUT} with {len(places)} places from {len(files)} images")

if __name__ == '__main__':
    main()
