#!/usr/bin/env python3
"""
Upload travel photos to Firebase Storage from any local folder.
Photos never enter the git repo — only places.js is updated.

Usage:
  python3 upload-travel.py ~/Photos/vacation/     # upload a folder
  python3 upload-travel.py photo1.jpg photo2.jpg   # upload specific files
  python3 upload-travel.py --sync                  # regenerate places.js from Firebase cache
"""

import os, sys, json, time, subprocess, hashlib
from PIL import Image
from PIL.ExifTags import TAGS, GPSTAGS

OUTPUT = 'assets/js/places.js'

# Firebase config
FB_DB_URL = 'https://zhaomin-homepage-default-rtdb.firebaseio.com'
FB_BUCKET = 'zhaomin-homepage.firebasestorage.app'
FB_STORAGE_API = f'https://firebasestorage.googleapis.com/v0/b/{FB_BUCKET}'

SUPPORTED_EXT = ('.jpg', '.jpeg', '.png', '.webp', '.heic')

def file_hash(path):
    h = hashlib.md5()
    with open(path, 'rb') as f:
        while True:
            chunk = f.read(8192)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()

def get_exif_gps(path):
    try:
        img = Image.open(path)
        exif = img._getexif()
        if not exif:
            return None
        gps_info = {}
        date = ''
        for tag_id, value in exif.items():
            tag = TAGS.get(tag_id, tag_id)
            if tag == 'GPSInfo':
                for gps_tag_id, gps_value in value.items():
                    gps_tag = GPSTAGS.get(gps_tag_id, gps_tag_id)
                    gps_info[gps_tag] = gps_value
            elif tag == 'DateTimeOriginal' or (tag == 'DateTime' and not date):
                date = str(value)
        if not gps_info:
            return None
        def to_decimal(dms, ref):
            d, m, s = [float(x) for x in dms]
            decimal = d + m/60 + s/3600
            if ref in ('S', 'W'):
                decimal = -decimal
            return round(decimal, 6)
        lat = to_decimal(gps_info.get('GPSLatitude', (0,0,0)), gps_info.get('GPSLatitudeRef', 'N'))
        lng = to_decimal(gps_info.get('GPSLongitude', (0,0,0)), gps_info.get('GPSLongitudeRef', 'E'))
        return {'lat': lat, 'lng': lng, 'date': date[:10].replace(':', '-') if date else ''}
    except Exception as e:
        print(f"  Warning: {e}")
        return None

def reverse_geocode(lat, lng):
    try:
        url = f'https://nominatim.openstreetmap.org/reverse?lat={lat}&lon={lng}&format=json&zoom=10'
        result = subprocess.run(['curl', '-s', url, '-H', 'User-Agent: travel-upload/1.0'],
                                capture_output=True, text=True, timeout=15)
        data = json.loads(result.stdout)
        addr = data.get('address', {})
        city = addr.get('city') or addr.get('town') or addr.get('village') or addr.get('county') or ''
        state = addr.get('state') or addr.get('country') or ''
        if city and state:
            return f'{city}, {state}'
        return city or state or f'{lat:.2f}, {lng:.2f}'
    except:
        return f'{lat:.2f}, {lng:.2f}'

def fb_load_cache():
    try:
        result = subprocess.run(['curl', '-s', f'{FB_DB_URL}/travel-cache.json'],
                                capture_output=True, text=True, timeout=10)
        data = json.loads(result.stdout)
        if data and isinstance(data, dict) and 'photos' in data:
            return data
    except:
        pass
    return {'photos': {}, 'geocode': {}}

def fb_save_cache(cache):
    try:
        tmp = '/tmp/travel-cache-upload.json'
        with open(tmp, 'w') as f:
            json.dump(cache, f)
        subprocess.run(['curl', '-s', '-X', 'PUT', '-H', 'Content-Type: application/json',
                        '--data-binary', f'@{tmp}', f'{FB_DB_URL}/travel-cache.json'],
                       capture_output=True, text=True, timeout=30)
        os.remove(tmp)
        print('  ☁ Cache saved to Firebase')
    except Exception as e:
        print(f'  ☁ Cache save failed: {e}')

def fb_upload_photo(local_path, filename):
    try:
        ext = filename.lower().rsplit('.', 1)[-1]
        ct = {'jpg': 'image/jpeg', 'jpeg': 'image/jpeg', 'png': 'image/png', 'webp': 'image/webp'}.get(ext, 'image/jpeg')
        encoded_name = f'travel/{filename}'.replace('/', '%2F')
        upload_url = f'{FB_STORAGE_API}/o?uploadType=media&name=travel/{filename}'
        result = subprocess.run(['curl', '-s', '-X', 'POST', '-H', f'Content-Type: {ct}',
                                 '--data-binary', f'@{local_path}', upload_url],
                                capture_output=True, text=True, timeout=120)
        resp = json.loads(result.stdout)
        if 'name' in resp:
            return f'{FB_STORAGE_API}/o/{encoded_name}?alt=media'
    except:
        pass
    return None

def generate_places_js(cache):
    places = list(cache.get('photos', {}).values())
    places = [p['data'] for p in places if 'data' in p]
    places.sort(key=lambda p: p.get('date', ''), reverse=True)

    js = [
        '/*',
        ' * places.js — Auto-generated by upload-travel.py',
        ' * Photos hosted on Firebase Storage.',
        ' * DO NOT EDIT MANUALLY.',
        ' */',
        f'const PLACES = {json.dumps(places, indent=2)};',
    ]
    with open(OUTPUT, 'w') as f:
        f.write('\n'.join(js) + '\n')
    print(f'\n  Generated {OUTPUT} with {len(places)} places')

def collect_files(args):
    files = []
    for arg in args:
        if os.path.isdir(arg):
            for f in sorted(os.listdir(arg)):
                if f.lower().endswith(SUPPORTED_EXT):
                    files.append(os.path.join(arg, f))
        elif os.path.isfile(arg) and arg.lower().endswith(SUPPORTED_EXT):
            files.append(arg)
    return files

def main():
    args = sys.argv[1:]

    if not args:
        print('Usage:')
        print('  python3 upload-travel.py ~/Photos/vacation/   # upload a folder')
        print('  python3 upload-travel.py photo1.jpg            # upload specific files')
        print('  python3 upload-travel.py --sync                # regenerate places.js from cache')
        return

    cache = fb_load_cache()
    photo_cache = cache.get('photos', {})
    geo_cache = cache.get('geocode', {})

    if args == ['--sync']:
        print('Syncing places.js from Firebase cache...')
        print(f'  {len(photo_cache)} photos in cache')
        generate_places_js(cache)
        return

    files = collect_files(args)
    if not files:
        print('No supported image files found.')
        return

    print(f'Found {len(files)} photos to process\n')
    new_count = 0
    skip_count = 0

    for filepath in files:
        filename = os.path.basename(filepath)
        fhash = file_hash(filepath)

        if filename in photo_cache and photo_cache[filename].get('hash') == fhash:
            print(f'  ⏭ {filename} (already uploaded)')
            skip_count += 1
            continue

        print(f'  📷 {filename}')

        gps = get_exif_gps(filepath)
        if not gps:
            print(f'     ✗ No GPS data, skipping')
            continue

        # Geocode
        coord_key = f"{gps['lat']:.1f},{gps['lng']:.1f}"
        if coord_key not in geo_cache:
            location = reverse_geocode(gps['lat'], gps['lng'])
            geo_cache[coord_key] = location
            time.sleep(1)
        else:
            location = geo_cache[coord_key]

        # Upload
        print(f'     Uploading to Firebase...')
        cdn_url = fb_upload_photo(filepath, filename)
        if not cdn_url:
            print(f'     ✗ Upload failed, skipping')
            continue

        entry = {
            'file': filename,
            'lat': gps['lat'],
            'lng': gps['lng'],
            'date': gps['date'],
            'location': location,
            'url': cdn_url,
        }
        photo_cache[filename] = {'hash': fhash, 'data': entry}
        new_count += 1
        print(f'     ✓ {location} ({gps["date"]})')

    cache['photos'] = photo_cache
    cache['geocode'] = geo_cache
    fb_save_cache(cache)
    generate_places_js(cache)

    print(f'\nDone: {new_count} uploaded, {skip_count} skipped (already in cache)')

if __name__ == '__main__':
    main()
